Add electron build workflow
duckdb/duckdb-node pull request #100
Opened 2024-06-18 11:18 UTC by azmy60

In attempt to support electron build as mentioned in #70.

This PR aims to build a binary for electron `18.3.x`.

2024-07-13 20:36 UTC, carlopi commented on .github/workflows/Electron.yml
> +          ELECTRON_VERSION: {{{ matrix.version.electron }}}
```suggestion
          ELECTRON_VERSION: ${{ matrix.version.electron }}
```
Probably like this

2024-07-13 20:39 UTC, carlopi requested changes
I think those syntax need changing

2024-07-13 20:39 UTC, carlopi commented on .github/workflows/Electron.yml
> +          ELECTRON_VERSION: {{{ matrix.version.electron }}}
```suggestion
          ELECTRON_VERSION: ${{ matrix.version.electron }}
```

2024-07-13 20:39 UTC, carlopi commented on .github/workflows/Electron.yml
> +          ELECTRON_VERSION: {{{ matrix.version.electron }}}
```suggestion
          ELECTRON_VERSION: ${{ matrix.version.electron }}
```

2024-07-13 20:39 UTC, carlopi commented on .github/workflows/Electron.yml
> +          ELECTRON_VERSION: {{{ matrix.version.electron }}}
```suggestion
          ELECTRON_VERSION: ${{ matrix.version.electron }}
```

2024-07-13 20:41 UTC, carlopi commented on .github/workflows/Electron.yml
> +  win-nodejs:
```suggestion
  win-electron:
```

2024-07-13 20:44 UTC, carlopi commented
Thanks for the contribution, could you have a look at why CI is failing?

2024-07-15 05:41 UTC, azmy60 commented
@carlopi So it was failing because I needed to add the patch version to the `electron-versions.json`. It should be working now.

2024-07-15 07:12 UTC, carlopi requested changes
Thanks, looks good, last request, could you make it so only a small subset (say up to 3?) of the electron builds are actually run on pull requests?

I could also take a look at tweaking this at some later point, but I think having like the setup step be conditional, and either use the full matrix or only selected rows it would be handy to have, since otherwise this will become very heavy.

2024-07-15 09:27 UTC, carlopi approved these changes
Thanks!!

2024-07-15 09:28 UTC, azmy60 commented
No problem! I just filtered 2 versions that we're currently using in our repo now. :)

2024-07-15 10:21 UTC, merged

2024-07-15 10:55 UTC, carlopi commented
@azmy60: given you have it still fresh, could you take a look at the syntax that triggers this problem https://github.com/duckdb/duckdb-node/actions/runs/9937704658: 
 ```
--
Error when evaluating 'strategy' for job 'osx-electron-x64'. .github/workflows/Electron.yml (Line: 167, Col: 18): Error parsing fromJson,.github/workflows/Electron.yml (Line: 167, Col: 18): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/Electron.yml (Line: 167, Col: 18): Unexpected value ''Show less
 

<br class="Apple-interchange-newline">
```